name: SGPO
channels:
  - conda-forge
  - defaults
  - bioconda  # for mafft and mmseqs2
dependencies:
  - python=3.10
  - pytorch  # handled via conda for GPU compatibility if needed
  - lightning
  - transformers
  - wandb
  - ipykernel
  - biopython
  - mmseqs2
  - mafft
  - timm
  - botorch
  - pip
  - seaborn
  - pip:
    - hydra-core
    - evodiff