name: protein_NOS
sample_batch_size: 200 #batch size for inference

train:
  batch_size: 64 #batch size for training
  n_epochs: 200 #200, test with a smaller amount for now, not sure how much this requires
  seed: 42
  # learning_rate: 1e-3
  device: cuda
  wandb: True

#don't know if i understand this part
# model:
#   _target_: problem.basic.XOR
#   ratio: 0.5
data:
  _target_: dataset.protein.ProteinPredictorDataset

model:
  _target_: training.train_classifier_NOS.Classifier
  config:
    classifier_backbone: dit # backbone for the classifier, currently only supports this
    time_conditioning: True
    optim:
      weight_decay: 0
      lr: 3e-4
      beta1: 0.9
      beta2: 0.999
      eps: 1e-8
    lr_scheduler:
      _target_: transformers.get_constant_schedule_with_warmup #check if constant warmup is fine
      num_warmup_steps: 2500
    model:
      _target_: models.MDLM.models.dit.DITClassifier
      model_config:
        classifier_model:
          name: small
          type: ddit
          hidden_size: 768
          cond_dim: 128
          #length: ${model.length}  # Same length as diffusion model
          length: 1024 #hardcoded for now
          n_blocks: 12
          n_heads: 12
          scale_by_sigma: True
          dropout: 0.1
          # num_classes: ${data.num_classes}
          pooling: mean
        # vocab_size: 31 #automatically determined

train_function:
  _target_: training.train_classifier_NOS.train_classifier

exp_dir: exps/protein

# evaluator:
#   _target_: eval.Evaluator
#   residues: [183, 184, 227, 228]
#   data_path: data/fitness.csv
