name: CreiLOV_protein
model:
  _target_: problem.basic.XOR
  ratio: 0.5
  length: 389

data:
  _target_: data.protein.ProteinPredictorDataset
  data_config:
    name: CreiLOV
    data_path: data/CreiLOV_fitness.csv
    full_seq: MAGLRHTFVVADATLPDCPLVYASEGFYAMTGYGPDEVLGHNARFLQGEGTDPKEVQKIRDAIKKGEACSVRLLNYRKDGTPFWNLLTVTPIKTPDGRVSKFVGVQVDVTSKTEGKALA
    seq_len: 119
    residues: None #mutated positions, this uses 1 indexing
    # tokenizer: #use the one from evodiff
    n_samples: 5000
    seed: 42
    alphabet_size: 26
exp_dir: exps/protein

