name: DAPS
time_conditioned: False
guidance_params: [2.5e3, 5e3, 1e4, 2e4, 4e4] #[0.1, 0.5, 1., 5., 25.] #[1., 10., 100., 1000., 10000.] [4., 16., 64., 256., 1024.]
method:
  _target_: sampling.daps.DAPS_continuous
  num_steps: 50 #100 #500
  ode_steps: 10
  lgvd_steps: 100
  alpha: 1 #default value
  n_max_mutations: