name: CreiLOV_full
data_path: data/CreiLOV_fitness.csv
full_seq: MAGLRHTFVVADATLPDCPLVYASEGFYAMTGYGPDEVLGHNARFLQGEGTDPKEVQKIRDAIKKGEACSVRLLNYRKDGTPFWNLLTVTPIKTPDGRVSKFVGVQVDVTSKTEGKALA
seq_len: 119
residues: #mutated positions, this uses 1 indexing, if None, then use all residues
seed: 42
alphabet_size: 26 #don't hardcode this in the future
pretraining:
  dataset_path: data/CreiLOV_MSA_full.csv
  splits: [train, validation]