name: TrpB_aligned
data_path: data/TrpB_fitness.csv
full_seq: MKGYFGPYGGQYVPEILMGALEELEAAYEGIMKDESFWKEFNDLLRDYAGRPTPLYFARRLSEKYGARVYLKREDLLHTGAHKINNAIGQVLLAKLMGKTRIIAETGAGQHGVATATAAALFGMECVIYMGEEDTIRQKLNVERMKLLGAKVVPVKSGSRTLKDAIDEALRDWITNLQTTYYVFGSVVGPHPYPIIVRNFQKVIGEETKKQIPEKEGRLPDYIVACVSGGSNAAGIFYPFIDSGVKLIGVEAGGEGLETGKHAASLLKGKIGYLHGSKTFVLQDDWGQVQVSHSVSAGLDYSGVGPEHAYWRETGKVLYDAVTDEEALDAFIELSRLEGIIPALESSHALAYLKKINIKGKVVVVNLSGRGDKDLESVLNHPYVRERIR
seq_len: 389
residues: [117, 118, 119, 162, 166, 182, 183, 184, 185, 186, 227, 228, 230, 231, 301] #mutated positions, this uses 1 indexing, if None, then use all residues
seed: 42
alphabet: 'ACDEFGHIKLMNPQRSTVWYBZXJOU' #don't hardcode this in the future
alphabet_size: 26 #don't hardcode this in the future