exp_name: baseline
num_samples: 100 #number of samples per round
random_init: False
seed: 42
n_repeats: 5
n_rounds: 8
pretrained_ckpt: d3pm_finetune/TrpB #continuous/TrpB

defaults:
  - data: TrpB
  - model: d3pm
  - problem: protein_classifier_discrete
  - algorithm: cls_guidance_discrete